apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swarsetu-ingress       # Name of the Ingress
  namespace: "2401202"         # YOUR Correct Namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: swarsetu.imcc.com  # The domain you will use to access the app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service  # Points to your REACT FRONTEND
                port:
                  number: 80            # Port 80 (Standard HTTP)